[package]
name = "some-rust"
version = "0.1.0"
authors = ["Bolaji Olajide"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "some-rust"
path = "main.rs"
